package com.yzf.thrift; /**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import org.apache.thrift.TException;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;
import org.apache.thrift.scheme.TupleScheme;

import javax.annotation.Generated;
import java.util.*;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2018-7-7")
public class action_req_t implements org.apache.thrift.TBase<action_req_t, action_req_t._Fields>, java.io.Serializable, Cloneable, Comparable<action_req_t> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("action_req_t");

  private static final org.apache.thrift.protocol.TField ORG_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("orgNo", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField MER_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("merNo", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ACTION_FIELD_DESC = new org.apache.thrift.protocol.TField("action", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField ENCRYPTKEY_FIELD_DESC = new org.apache.thrift.protocol.TField("encryptkey", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField VERSION_FIELD_DESC = new org.apache.thrift.protocol.TField("version", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField SIGN_FIELD_DESC = new org.apache.thrift.protocol.TField("sign", org.apache.thrift.protocol.TType.STRING, (short)7);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new action_req_tStandardSchemeFactory());
    schemes.put(TupleScheme.class, new action_req_tTupleSchemeFactory());
  }

  public String orgNo; // optional
  public String merNo; // optional
  public String action; // optional
  public String data; // optional
  public String encryptkey; // optional
  public String version; // optional
  public String sign; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ORG_NO((short)1, "orgNo"),
    MER_NO((short)2, "merNo"),
    ACTION((short)3, "action"),
    DATA((short)4, "data"),
    ENCRYPTKEY((short)5, "encryptkey"),
    VERSION((short)6, "version"),
    SIGN((short)7, "sign");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ORG_NO
          return ORG_NO;
        case 2: // MER_NO
          return MER_NO;
        case 3: // ACTION
          return ACTION;
        case 4: // DATA
          return DATA;
        case 5: // ENCRYPTKEY
          return ENCRYPTKEY;
        case 6: // VERSION
          return VERSION;
        case 7: // SIGN
          return SIGN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.ORG_NO, _Fields.MER_NO, _Fields.ACTION, _Fields.DATA, _Fields.ENCRYPTKEY, _Fields.VERSION, _Fields.SIGN};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ORG_NO, new org.apache.thrift.meta_data.FieldMetaData("orgNo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MER_NO, new org.apache.thrift.meta_data.FieldMetaData("merNo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ACTION, new org.apache.thrift.meta_data.FieldMetaData("action", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENCRYPTKEY, new org.apache.thrift.meta_data.FieldMetaData("encryptkey", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERSION, new org.apache.thrift.meta_data.FieldMetaData("version", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SIGN, new org.apache.thrift.meta_data.FieldMetaData("sign", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(action_req_t.class, metaDataMap);
  }

  public action_req_t() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public action_req_t(action_req_t other) {
    if (other.isSetOrgNo()) {
      this.orgNo = other.orgNo;
    }
    if (other.isSetMerNo()) {
      this.merNo = other.merNo;
    }
    if (other.isSetAction()) {
      this.action = other.action;
    }
    if (other.isSetData()) {
      this.data = other.data;
    }
    if (other.isSetEncryptkey()) {
      this.encryptkey = other.encryptkey;
    }
    if (other.isSetVersion()) {
      this.version = other.version;
    }
    if (other.isSetSign()) {
      this.sign = other.sign;
    }
  }

  public action_req_t deepCopy() {
    return new action_req_t(this);
  }

  @Override
  public void clear() {
    this.orgNo = null;
    this.merNo = null;
    this.action = null;
    this.data = null;
    this.encryptkey = null;
    this.version = null;
    this.sign = null;
  }

  public String getOrgNo() {
    return this.orgNo;
  }

  public action_req_t setOrgNo(String orgNo) {
    this.orgNo = orgNo;
    return this;
  }

  public void unsetOrgNo() {
    this.orgNo = null;
  }

  /** Returns true if field orgNo is set (has been assigned a value) and false otherwise */
  public boolean isSetOrgNo() {
    return this.orgNo != null;
  }

  public void setOrgNoIsSet(boolean value) {
    if (!value) {
      this.orgNo = null;
    }
  }

  public String getMerNo() {
    return this.merNo;
  }

  public action_req_t setMerNo(String merNo) {
    this.merNo = merNo;
    return this;
  }

  public void unsetMerNo() {
    this.merNo = null;
  }

  /** Returns true if field merNo is set (has been assigned a value) and false otherwise */
  public boolean isSetMerNo() {
    return this.merNo != null;
  }

  public void setMerNoIsSet(boolean value) {
    if (!value) {
      this.merNo = null;
    }
  }

  public String getAction() {
    return this.action;
  }

  public action_req_t setAction(String action) {
    this.action = action;
    return this;
  }

  public void unsetAction() {
    this.action = null;
  }

  /** Returns true if field action is set (has been assigned a value) and false otherwise */
  public boolean isSetAction() {
    return this.action != null;
  }

  public void setActionIsSet(boolean value) {
    if (!value) {
      this.action = null;
    }
  }

  public String getData() {
    return this.data;
  }

  public action_req_t setData(String data) {
    this.data = data;
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been assigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  public String getEncryptkey() {
    return this.encryptkey;
  }

  public action_req_t setEncryptkey(String encryptkey) {
    this.encryptkey = encryptkey;
    return this;
  }

  public void unsetEncryptkey() {
    this.encryptkey = null;
  }

  /** Returns true if field encryptkey is set (has been assigned a value) and false otherwise */
  public boolean isSetEncryptkey() {
    return this.encryptkey != null;
  }

  public void setEncryptkeyIsSet(boolean value) {
    if (!value) {
      this.encryptkey = null;
    }
  }

  public String getVersion() {
    return this.version;
  }

  public action_req_t setVersion(String version) {
    this.version = version;
    return this;
  }

  public void unsetVersion() {
    this.version = null;
  }

  /** Returns true if field version is set (has been assigned a value) and false otherwise */
  public boolean isSetVersion() {
    return this.version != null;
  }

  public void setVersionIsSet(boolean value) {
    if (!value) {
      this.version = null;
    }
  }

  public String getSign() {
    return this.sign;
  }

  public action_req_t setSign(String sign) {
    this.sign = sign;
    return this;
  }

  public void unsetSign() {
    this.sign = null;
  }

  /** Returns true if field sign is set (has been assigned a value) and false otherwise */
  public boolean isSetSign() {
    return this.sign != null;
  }

  public void setSignIsSet(boolean value) {
    if (!value) {
      this.sign = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ORG_NO:
      if (value == null) {
        unsetOrgNo();
      } else {
        setOrgNo((String)value);
      }
      break;

    case MER_NO:
      if (value == null) {
        unsetMerNo();
      } else {
        setMerNo((String)value);
      }
      break;

    case ACTION:
      if (value == null) {
        unsetAction();
      } else {
        setAction((String)value);
      }
      break;

    case DATA:
      if (value == null) {
        unsetData();
      } else {
        setData((String)value);
      }
      break;

    case ENCRYPTKEY:
      if (value == null) {
        unsetEncryptkey();
      } else {
        setEncryptkey((String)value);
      }
      break;

    case VERSION:
      if (value == null) {
        unsetVersion();
      } else {
        setVersion((String)value);
      }
      break;

    case SIGN:
      if (value == null) {
        unsetSign();
      } else {
        setSign((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ORG_NO:
      return getOrgNo();

    case MER_NO:
      return getMerNo();

    case ACTION:
      return getAction();

    case DATA:
      return getData();

    case ENCRYPTKEY:
      return getEncryptkey();

    case VERSION:
      return getVersion();

    case SIGN:
      return getSign();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ORG_NO:
      return isSetOrgNo();
    case MER_NO:
      return isSetMerNo();
    case ACTION:
      return isSetAction();
    case DATA:
      return isSetData();
    case ENCRYPTKEY:
      return isSetEncryptkey();
    case VERSION:
      return isSetVersion();
    case SIGN:
      return isSetSign();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof action_req_t)
      return this.equals((action_req_t)that);
    return false;
  }

  public boolean equals(action_req_t that) {
    if (that == null)
      return false;

    boolean this_present_orgNo = true && this.isSetOrgNo();
    boolean that_present_orgNo = true && that.isSetOrgNo();
    if (this_present_orgNo || that_present_orgNo) {
      if (!(this_present_orgNo && that_present_orgNo))
        return false;
      if (!this.orgNo.equals(that.orgNo))
        return false;
    }

    boolean this_present_merNo = true && this.isSetMerNo();
    boolean that_present_merNo = true && that.isSetMerNo();
    if (this_present_merNo || that_present_merNo) {
      if (!(this_present_merNo && that_present_merNo))
        return false;
      if (!this.merNo.equals(that.merNo))
        return false;
    }

    boolean this_present_action = true && this.isSetAction();
    boolean that_present_action = true && that.isSetAction();
    if (this_present_action || that_present_action) {
      if (!(this_present_action && that_present_action))
        return false;
      if (!this.action.equals(that.action))
        return false;
    }

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    boolean this_present_encryptkey = true && this.isSetEncryptkey();
    boolean that_present_encryptkey = true && that.isSetEncryptkey();
    if (this_present_encryptkey || that_present_encryptkey) {
      if (!(this_present_encryptkey && that_present_encryptkey))
        return false;
      if (!this.encryptkey.equals(that.encryptkey))
        return false;
    }

    boolean this_present_version = true && this.isSetVersion();
    boolean that_present_version = true && that.isSetVersion();
    if (this_present_version || that_present_version) {
      if (!(this_present_version && that_present_version))
        return false;
      if (!this.version.equals(that.version))
        return false;
    }

    boolean this_present_sign = true && this.isSetSign();
    boolean that_present_sign = true && that.isSetSign();
    if (this_present_sign || that_present_sign) {
      if (!(this_present_sign && that_present_sign))
        return false;
      if (!this.sign.equals(that.sign))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_orgNo = true && (isSetOrgNo());
    list.add(present_orgNo);
    if (present_orgNo)
      list.add(orgNo);

    boolean present_merNo = true && (isSetMerNo());
    list.add(present_merNo);
    if (present_merNo)
      list.add(merNo);

    boolean present_action = true && (isSetAction());
    list.add(present_action);
    if (present_action)
      list.add(action);

    boolean present_data = true && (isSetData());
    list.add(present_data);
    if (present_data)
      list.add(data);

    boolean present_encryptkey = true && (isSetEncryptkey());
    list.add(present_encryptkey);
    if (present_encryptkey)
      list.add(encryptkey);

    boolean present_version = true && (isSetVersion());
    list.add(present_version);
    if (present_version)
      list.add(version);

    boolean present_sign = true && (isSetSign());
    list.add(present_sign);
    if (present_sign)
      list.add(sign);

    return list.hashCode();
  }

  @Override
  public int compareTo(action_req_t other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOrgNo()).compareTo(other.isSetOrgNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrgNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.orgNo, other.orgNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMerNo()).compareTo(other.isSetMerNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMerNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.merNo, other.merNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAction()).compareTo(other.isSetAction());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAction()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.action, other.action);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetData()).compareTo(other.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, other.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEncryptkey()).compareTo(other.isSetEncryptkey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEncryptkey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.encryptkey, other.encryptkey);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetVersion()).compareTo(other.isSetVersion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVersion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.version, other.version);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSign()).compareTo(other.isSetSign());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSign()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sign, other.sign);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("action_req_t(");
    boolean first = true;

    if (isSetOrgNo()) {
      sb.append("orgNo:");
      if (this.orgNo == null) {
        sb.append("null");
      } else {
        sb.append(this.orgNo);
      }
      first = false;
    }
    if (isSetMerNo()) {
      if (!first) sb.append(", ");
      sb.append("merNo:");
      if (this.merNo == null) {
        sb.append("null");
      } else {
        sb.append(this.merNo);
      }
      first = false;
    }
    if (isSetAction()) {
      if (!first) sb.append(", ");
      sb.append("action:");
      if (this.action == null) {
        sb.append("null");
      } else {
        sb.append(this.action);
      }
      first = false;
    }
    if (isSetData()) {
      if (!first) sb.append(", ");
      sb.append("data:");
      if (this.data == null) {
        sb.append("null");
      } else {
        sb.append(this.data);
      }
      first = false;
    }
    if (isSetEncryptkey()) {
      if (!first) sb.append(", ");
      sb.append("encryptkey:");
      if (this.encryptkey == null) {
        sb.append("null");
      } else {
        sb.append(this.encryptkey);
      }
      first = false;
    }
    if (isSetVersion()) {
      if (!first) sb.append(", ");
      sb.append("version:");
      if (this.version == null) {
        sb.append("null");
      } else {
        sb.append(this.version);
      }
      first = false;
    }
    if (isSetSign()) {
      if (!first) sb.append(", ");
      sb.append("sign:");
      if (this.sign == null) {
        sb.append("null");
      } else {
        sb.append(this.sign);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class action_req_tStandardSchemeFactory implements SchemeFactory {
    public action_req_tStandardScheme getScheme() {
      return new action_req_tStandardScheme();
    }
  }

  private static class action_req_tStandardScheme extends StandardScheme<action_req_t> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, action_req_t struct) throws TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ORG_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.orgNo = iprot.readString();
              struct.setOrgNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MER_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.merNo = iprot.readString();
              struct.setMerNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ACTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.action = iprot.readString();
              struct.setActionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.data = iprot.readString();
              struct.setDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ENCRYPTKEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.encryptkey = iprot.readString();
              struct.setEncryptkeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // VERSION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.version = iprot.readString();
              struct.setVersionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SIGN
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sign = iprot.readString();
              struct.setSignIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, action_req_t struct) throws TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.orgNo != null) {
        if (struct.isSetOrgNo()) {
          oprot.writeFieldBegin(ORG_NO_FIELD_DESC);
          oprot.writeString(struct.orgNo);
          oprot.writeFieldEnd();
        }
      }
      if (struct.merNo != null) {
        if (struct.isSetMerNo()) {
          oprot.writeFieldBegin(MER_NO_FIELD_DESC);
          oprot.writeString(struct.merNo);
          oprot.writeFieldEnd();
        }
      }
      if (struct.action != null) {
        if (struct.isSetAction()) {
          oprot.writeFieldBegin(ACTION_FIELD_DESC);
          oprot.writeString(struct.action);
          oprot.writeFieldEnd();
        }
      }
      if (struct.data != null) {
        if (struct.isSetData()) {
          oprot.writeFieldBegin(DATA_FIELD_DESC);
          oprot.writeString(struct.data);
          oprot.writeFieldEnd();
        }
      }
      if (struct.encryptkey != null) {
        if (struct.isSetEncryptkey()) {
          oprot.writeFieldBegin(ENCRYPTKEY_FIELD_DESC);
          oprot.writeString(struct.encryptkey);
          oprot.writeFieldEnd();
        }
      }
      if (struct.version != null) {
        if (struct.isSetVersion()) {
          oprot.writeFieldBegin(VERSION_FIELD_DESC);
          oprot.writeString(struct.version);
          oprot.writeFieldEnd();
        }
      }
      if (struct.sign != null) {
        if (struct.isSetSign()) {
          oprot.writeFieldBegin(SIGN_FIELD_DESC);
          oprot.writeString(struct.sign);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class action_req_tTupleSchemeFactory implements SchemeFactory {
    public action_req_tTupleScheme getScheme() {
      return new action_req_tTupleScheme();
    }
  }

  private static class action_req_tTupleScheme extends TupleScheme<action_req_t> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, action_req_t struct) throws TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetOrgNo()) {
        optionals.set(0);
      }
      if (struct.isSetMerNo()) {
        optionals.set(1);
      }
      if (struct.isSetAction()) {
        optionals.set(2);
      }
      if (struct.isSetData()) {
        optionals.set(3);
      }
      if (struct.isSetEncryptkey()) {
        optionals.set(4);
      }
      if (struct.isSetVersion()) {
        optionals.set(5);
      }
      if (struct.isSetSign()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetOrgNo()) {
        oprot.writeString(struct.orgNo);
      }
      if (struct.isSetMerNo()) {
        oprot.writeString(struct.merNo);
      }
      if (struct.isSetAction()) {
        oprot.writeString(struct.action);
      }
      if (struct.isSetData()) {
        oprot.writeString(struct.data);
      }
      if (struct.isSetEncryptkey()) {
        oprot.writeString(struct.encryptkey);
      }
      if (struct.isSetVersion()) {
        oprot.writeString(struct.version);
      }
      if (struct.isSetSign()) {
        oprot.writeString(struct.sign);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, action_req_t struct) throws TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.orgNo = iprot.readString();
        struct.setOrgNoIsSet(true);
      }
      if (incoming.get(1)) {
        struct.merNo = iprot.readString();
        struct.setMerNoIsSet(true);
      }
      if (incoming.get(2)) {
        struct.action = iprot.readString();
        struct.setActionIsSet(true);
      }
      if (incoming.get(3)) {
        struct.data = iprot.readString();
        struct.setDataIsSet(true);
      }
      if (incoming.get(4)) {
        struct.encryptkey = iprot.readString();
        struct.setEncryptkeyIsSet(true);
      }
      if (incoming.get(5)) {
        struct.version = iprot.readString();
        struct.setVersionIsSet(true);
      }
      if (incoming.get(6)) {
        struct.sign = iprot.readString();
        struct.setSignIsSet(true);
      }
    }
  }

}

